# standard settings
server:
  type: default
  gzip:
    enabled: true
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
# my config settings
template: hello
emailTimer: 1000